// API
relic_sets = [
    'Band of Sizzling Thunder',
    'Belobog of the Architects',
    'Celestial Differentiator',
    'Champion of Streetwise Boxing',
    'Eagle of Twilight Line',
    'Firesmith of Lava-Forging',
    'Fleet of the Ageless',
    'Genius of the Brilliant Stars',
    'Guard of Wuthering Snow',
    'Hunter of Glacial Forest',
    'Inert Salsotto',
    'Knight of Purity Palace',
    'Musketeer of Wild Wheat',
    'Pan-Galactic Commercial Enterprise',
    'Passerby of Wandering Cloud',
    'Space Sealing Station',
    'Sprightly Vonwacq',
    'Talia: Kingdom of Banditry',
    'Thief of Shooting Meteor',
    'Wastelander of Banditry Desert',
];
relic_types = [
    'head',
    'hands',
    'body',
    'feet',
    'planar sphere',
    'link rope',
];
stats = [
    'hp',
    'atk',
    'def',
    'critRate',
    'critDMG',
    'outgoing_healing_boost',
    'effect_hit_rate',
    'effect_res',
    'break_effect',
    'spd',
];
characters = [
    'Arlan',
    'Asta',
    'Bailu',
    'Blade',
    'Bronya',
    'Clara',
    'Dan Heng',
    'Fu Xuan',
    'Gepard',
    'Herta',
    'Himeko',
    'Hook',
    'Jing Yuan',
    'Kafka',
    'Luka',
    'Luocha',
    'March 7th',
    'Natasha',
    'Pela',
    'Qingque',
    'Sampo',
    'Seele',
    'Serval',
    'Silverwolf',
    'Sushang',
    'Tingyun',
    'Trailblazer (Fire)',
    'Trailblazer (Physical)',
    'Welt',
    'Yanqing',
    'Yukong',
];
lightcones = {
    "Destruction": [
        "On the Fall of an Aeon",
        "Something Irreplaceable",
        "Nowhere to Run",
        "Woof! Walk Time!",
        "Under the Blue Sky",
        "A Secret Vow",
        "The Moles Welcome You",
        "Mutual Demise",
        "Shattered Home",
        "Collapsing Sky"
    ],
    "The Hunt": [
        "Cruising in the Stellar Sea",
        "Sleep Like the Dead",
        "In the Night",
        "Return to Darkness",
        "River Flows in Spring",
        "Subscribe for More!",
        "Swordplay",
        "Only Silence Remains",
        "Adversarial",
        "Darting Arrow",
        "Arrows"
    ],
    "Erudition": [
        "Before Dawn",
        "Night on the Milky Way",
        "Today Is Another Peaceful Day",
        "The Seriousness of Breakfast",
        "Geniuses' Repose",
        "Make the World Clamor",
        "The Birth of the Self",
        "Sagacity",
        "Passkey",
        "Data Bank"
    ],
    "Harmony": [
        "But the Battle Isn't Over",
        "Carve the Moon, Weave the Clouds",
        "Past and Future",
        "Dance! Dance! Dance!",
        "Planetary Rendezvous",
        "Memories of the Past",
        "Mediation",
        "Meshing Cogs",
        "Chorus"
    ],
    "Nihility": [
        "In the Name of the World",
        "We Will Meet Again",
        "Fermata",
        "Resolution Shines As Pearls of Sweat",
        "Eyes of the Prey",
        "Good Night and Sleep Well",
        "Hidden Shadow",
        "Loop",
        "Void"
    ],
    "Preservation": [
        "Texture of Memories",
        "Moment of Victory",
        "This Is Me!",
        "We Are Wildfire",
        "Trend of the Universal Market",
        "Landau's Choice",
        "Day One of My New Life",
        "Pioneering",
        "Defense",
        "Amber"
    ],
    "Abundance": [
        "Time Waits for No One",
        "Warmth Shortens Cold Nights",
        "Quid Pro Quo",
        "Perfect Timing",
        "Shared Feeling",
        "Post-Op Conversation",
        "Multiplication",
        "Fine Fruit",
        "Cornucopia"
    ]
}
levels = [
    "80",
    "70/80",
    "70",
    "60/70",
    "60",
    "50/60",
    "50",
    "40/50",
    "40",
    "30/40",
    "30",
    "20/30",
    "20",
    "1/20",
];

relicsetToJSONData = {
    'Passerby of Wandering Cloud': '101.json',
    'Musketeer of Wild Wheat': '102.json',
    'Knight of Purity Palace': '103.json',
    'Hunter of Glacial Forest': '104.json',
    'Champion of Streetwise Boxing': '105.json',
    'Guard of Wuthering Snow': '106.json',
    'Firesmith of Lava-Forging': '107.json',
    'Genius of Brilliant Stars': '108.json',
    'Band of Sizzling Thunder': '109.json',
    'Eagle of Twilight Line': '110.json',
    'Thief of Shooting Meteor': '111.json',
    'Wastelander of Banditry Desert': '112.json',
    'Space Sealing Station': '301.json',
    'Fleet of the Ageless': '302.json',
    'Pan-Galactic Commercial Enterprise': '303.json',
    'Belobog of the Architects': '304.json',
    'Celestial Differentiator': '305.json',
    'Inert Salsotto': '306.json',
    'Talia: Kingdom of Banditry': '307.json',
    'Sprightly Vonwacq': '308.json'
};
relicslotToID = {
    "Head": "1",
    "Hands": "2",
    "Body": "3",
    "Feet": "4",
    "Planar Sphere": "5",
    "Link Rope": "6",
}
lightconesToID = {
    'Arrows': '20000.json',
    'Cornucopia': '20001.json',
    'Collapsing Sky': '20002.json',
    'Amber': '20003.json',
    'Void': '20004.json',
    'Chorus': '20005.json',
    'Data Bank': '20006.json',
    'Darting Arrow': '20007.json',
    'Fine Fruit': '20008.json',
    'Shattered Home': '20009.json',
    'Defense': '20010.json',
    'Loop': '20011.json',
    'Meshing Cogs': '20012.json',
    'Passkey': '20013.json',
    'Adversarial': '20014.json',
    'Multiplication': '20015.json',
    'Mutual Demise': '20016.json',
    'Pioneering': '20017.json',
    'Hidden Shadow': '20018.json',
    'Mediation': '20019.json',
    'Sagacity': '20020.json',
    'Post-Op Conversation': '21000.json',
    'Good Night and Sleep Well': '21001.json',
    'Day One of My New Life': '21002.json',
    'Only Silence Remains': '21003.json',
    'Memories of the Past': '21004.json',
    'The Moles Welcome You': '21005.json',
    'The Birth of the Self': '21006.json',
    'Shared Feeling': '21007.json',
    'Eyes of the Prey': '21008.json',
    "Landau's Choice": '21009.json',
    'Swordplay': '21010.json',
    'Planetary Rendezvous': '21011.json',
    'A Secret Vow': '21012.json',
    'Make the World Clamor': '21013.json',
    'Perfect Timing': '21014.json',
    'Resolution Shines As Pearls of Sweat': '21015.json',
    'Trend of the Universal Market': '21016.json',
    'Subscribe for More!': '21017.json',
    'Dance! Dance! Dance!': '21018.json',
    'Under the Blue Sky': '21019.json',
    "Geniuses' Repose": '21020.json',
    'Quid Pro Quo': '21021.json',
    'Fermata': '21022.json',
    'We Are Wildfire': '21023.json',
    'River Flows in Spring': '21024.json',
    'Past and Future': '21025.json',
    'Woof! Walk Time!': '21026.json',
    'The Seriousness of Breakfast': '21027.json',
    'Warmth Shortens Cold Nights': '21028.json',
    'We Will Meet Again': '21029.json',
    'This Is Me!': '21030.json',
    'Return to Darkness': '21031.json',
    'Carve the Moon, Weave the Clouds': '21032.json',
    'Nowhere to Run': '21033.json',
    'Today Is Another Peaceful Day': '21034.json',
    'Night on the Milky Way': '23000.json',
    'In the Night': '23001.json',
    'Something Irreplaceable': '23002.json',
    "But the Battle Isn't Over": '23003.json',
    'In the Name of the World': '23004.json',
    'Moment of Victory': '23005.json',
    'Before Dawn': '23010.json',
    'Sleep Like the Dead': '23012.json',
    'Time Waits for No One': '23013.json',
    'On the Fall of an Aeon': '24000.json',
    'Cruising in the Stellar Sea': '24001.json',
    'Texture of Memories': '24002.json'
  }