export const CHARACTERS = [
    { label: 'Arlan', json: 'arlan.json' },
    { label: 'Asta', json: 'asta.json' },
    { label: 'Bailu', json: 'bailu.json' },
    { label: 'Blade', json: 'blade.json' },
    { label: 'Bronya', json: 'bronya.json' },
    { label: 'Clara', json: 'clara.json' },
    { label: 'Dan Heng', json: 'danheng.json' },
    { label: 'Fu Xuan', json: 'fuxuan.json' },
    { label: 'Gepard', json: 'gepard.json' },
    { label: 'Herta', json: 'herta.json' },
    { label: 'Himeko', json: 'himeko.json' },
    { label: 'Hook', json: 'hook.json' },
    { label: 'Jing Yuan', json: 'jingyuan.json' },
    { label: 'Kafka', json: 'kafka.json' },
    { label: 'Luka', json: 'luka.json' },
    { label: 'Luocha', json: 'luocha.json' },
    { label: 'March 7th', json: 'mar7th.json' },
    { label: 'Natasha', json: 'natasha.json' },
    { label: 'Pela', json: 'pela.json' },
    { label: 'Qingque', json: 'qingque.json' },
    { label: 'Sampo', json: 'sampo.json' },
    { label: 'Seele', json: 'seele.json' },
    { label: 'Serval', json: 'serval.json' },
    { label: 'Silverwolf', json: 'silverwolf.json' },
    { label: 'Sushang', json: 'sushang.json' },
    { label: 'Tingyun', json: 'tingyun.json' },
    { label: 'Trailblazer (Fire)', json: 'playergirl2.json' },
    { label: 'Trailblazer (Physical)', json: 'playergirl.json' },
    { label: 'Welt', json: 'welt.json' },
    { label: 'Yanqing', json: 'yanqing.json' },
    { label: 'Yukong', json: 'yukong.json' },
  ];
  